
//User Actions
export const SET_CURRENT_USER = "SET_CURRENT_USER"

//Cart Actions
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART"
export const REMOVE_ITEMS_FROM_CART = "REMOVE_ITEMS_FROM_CART"
export const INCREASE_ITEM_COUNT = "INCREASE_ITEM_COUNT"
export const DECREASE_ITEM_COUNT = "DECREASE_ITEM_COUNT"

//Items Actions
export const FETCH_ITEMS = "FETCH_ITEMS";